server:
  port: ${MARKETING_PORT:8091}
spring:
  application:
    name: coffee-marketing-service
  datasource:
    url: ${COFFEE_DB_URL:jdbc:mysql://localhost:3306/coffee_order_pro?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${COFFEE_DB_USERNAME}
    password: ${COFFEE_DB_PASSWORD}
  cloud:
    nacos:
      discovery:
        enabled: false
