package com.coffee.module.merchantagent.biz.application;

import com.coffee.common.core.exception.ServiceException;
import com.coffee.common.ai.ZhipuChatClient;
import com.coffee.module.merchantagent.api.MerchantGrowthAgentService;
import com.coffee.module.merchantagent.biz.domain.GrowthActionPolicy;
import com.coffee.module.merchantagent.biz.domain.GrowthActionType;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.math.BigDecimal;
import java.util.*;

/** 店长增长 Agent 应用层：数据诊断与工具执行，所有写动作均需要 Web 层确认商家归属。 */
@Service
public class MerchantGrowthAgentApplicationService implements MerchantGrowthAgentService {
    private final JdbcTemplate jdbc; private final ObjectMapper json; private final ZhipuChatClient chatClient; private final GrowthActionPolicy actionPolicy; private final String templateStoreCode; private final MerchantGrowthIntentParser intentParser = new MerchantGrowthIntentParser(); private static final int TARGET_LIMIT=30;
    public MerchantGrowthAgentApplicationService(JdbcTemplate jdbc, ObjectMapper json, ZhipuChatClient chatClient, GrowthActionPolicy actionPolicy, @Value("${coffee.ai.template-store-code:jingan}") String templateStoreCode){this.jdbc=jdbc;this.json=json;this.chatClient=chatClient;this.actionPolicy=actionPolicy;this.templateStoreCode=templateStoreCode;}
    @Override public Map<String,Object> analyze(Long storeId,String question){
        String q=question==null?"":question.trim();if(q.length()>300)throw new ServiceException(400,"问题不能超过 300 个字符");MerchantGrowthIntentParser.Intent intent=intentParser.parse(q);Map<String,Object>s=snapshot(storeId);int pending=((Number)s.get("pendingOrders")).intValue(),stock=((Number)s.get("flashSaleStock")).intValue(),orders=((Number)s.get("todayOrders")).intValue();
        List<Map<String,Object>> signals=new ArrayList<>();signals.add(signal("今日订单",orders+" 单",orders==0?"需要拉新或唤醒顾客":"保持关注"));signals.add(signal("今日营业额","¥"+money(((Number)s.get("todayRevenue")).doubleValue()),orders==0?"尚无已完成订单":"仅统计已完成订单"));if(pending>0)signals.add(signal("履约压力",pending+" 单待处理/制作",pending>3?"优先保证出品":"履约节奏可控"));if(stock>0)signals.add(signal("秒杀库存",stock+" 份可抢","可以通知近期顾客提高转化"));
        Map<String,Object> action=new LinkedHashMap<>();
        // 履约风险永远优先于营销诉求，避免 Agent 为了增长影响现场服务。
        if(intent.has(MerchantGrowthIntentParser.Focus.FULFILLMENT)||pending>3){action.put("actionType","NOTIFY_MEMBERS");action.put("title","服务节奏提醒 · 暂缓营销触达");action.put("summary","当前有 "+pending+" 单正在履约，建议先保证出品节奏，再考虑增长动作。");action.put("reason",pending>3?"待处理订单超过保护阈值 3 单。":"店长问题聚焦履约，先查看队列而不是发起营销。");action.put("proposal",Map.of("message","门店正在加紧制作，感谢你的耐心等待。","targetDays",1));}
        else if(intent.has(MerchantGrowthIntentParser.Focus.INVENTORY)&&stock>0){action.put("actionType","NOTIFY_MEMBERS");action.put("title","提醒顾客 · 限时秒杀库存充足");action.put("summary","当前仍有 "+stock+" 份可抢资格，建议只触达近期到店顾客。");action.put("reason","库存工具返回存在可抢名额。" );action.put("proposal",Map.of("message","你关注的 FIKA 限时尝鲜仍有名额，先到先得，来选一杯喜欢的吧。","targetDays",30));}
        else if(intent.has(MerchantGrowthIntentParser.Focus.PROMOTION)||intent.has(MerchantGrowthIntentParser.Focus.RETENTION)||intent.has(MerchantGrowthIntentParser.Focus.REVENUE)||intent.has(MerchantGrowthIntentParser.Focus.ORDERS)||orders==0){action.put("actionType","CREATE_VOUCHERS");action.put("title","老客唤醒 · 满48减8限时券");action.put("summary","建议向近 30 天到店顾客发放满 ¥48 减 ¥8 券，优先提高复购。");action.put("reason",orders==0?"今天尚未形成有效订单，需要轻量唤醒。":"问题聚焦增长且履约压力可控，适合小范围复购触达。" );action.put("proposal",Map.of("discount",8,"minimum",48,"targetDays",30,"expiresDays",3,"message","FIKA 为你留了一张满 ¥48 减 ¥8 的限时心意券，3 天内可用。"));}
        else{action.put("actionType","NOTIFY_MEMBERS");action.put("title","感谢到店 · 轻量回访");action.put("summary","今日经营稳定，建议做一次不带优惠的服务回访。");action.put("reason","订单和履约数据均处于正常区间。");action.put("proposal",Map.of("message","感谢你今天来到 FIKA。对这杯咖啡有任何建议，都欢迎告诉我们。","targetDays",7));}
        Map<String,Object> store=storeMeta(storeId);boolean template=templateStoreCode.equalsIgnoreCase(String.valueOf(store.get("code")));
        String fallback="我已调用订单、秒杀库存和履约数据工具完成诊断。";
        String role=template?"你是 FIKA・静安店的增长顾问。静安店是品牌经营表达的参考，但不要机械复用模板；像一位熟悉门店现场的店长搭档一样，说清判断与取舍。":"你是 FIKA「"+store.get("name")+"」的增长顾问，根据门店经营快照给出贴近现场、自然易懂的判断。";
        String answer=chatClient.chat(role+" 用 2-4 句中文回答店长问题，先说关键观察，再解释建议背后的取舍；表达可以自然、有观点，但不得修改或新增营销方案、优惠金额、触达范围，也不得声称已经执行。所有行动仍需店长确认。",
                "店长问题：" + (q.isBlank() ? "请给出经营建议" : q) + "\n需求理解：" + intent.summary() + "\n经营快照：" + s + "\n系统受控建议：" + action.get("summary") + "；原因：" + action.get("reason")).orElse(fallback);
        String engine=answer.equals(fallback)?"FIKA Growth Agent · rule-tools":template?"FIKA Growth Agent · 静安样板 GLM":"FIKA Growth Agent · 通用 GLM";
        return Map.of("answer",answer,"signals",signals,"snapshot",s,"understanding",intent.summary(),"dataSources",List.of("订单统计","履约队列","秒杀库存"),"suggestedAction",action,"engine",engine,"disclaimer","涉及营销触达必须由店长确认后执行。");
    }
    @Override public Long createAction(Long mid,Long sid,String type,String title,Map<String,Object> proposal){GrowthActionPolicy.ApprovedAction action=actionPolicy.approve(type,title,proposal);try{jdbc.update("INSERT INTO growth_agent_action (merchant_id,store_id,action_type,title,proposal_json,status,created_at) VALUES (?,?,?,?,?,'PENDING',NOW())",mid,sid,action.type().name(),action.title(),json.writeValueAsString(action.proposal()));return jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);}catch(ServiceException e){throw e;}catch(Exception e){throw migration(e);}}
    @Override public Map<String,Object> executeAction(Long mid,Long sid,Long id){try{List<Map<String,Object>> rows=jdbc.queryForList("SELECT action_type AS actionType,title,proposal_json AS proposalJson,status FROM growth_agent_action WHERE id=? AND merchant_id=? AND store_id=?",id,mid,sid);if(rows.isEmpty())throw new ServiceException(404,"Agent 操作不存在");Map<String,Object>a=rows.get(0);if(!"PENDING".equals(a.get("status")))throw new ServiceException(409,"该方案已经处理");if(jdbc.update("UPDATE growth_agent_action SET status='EXECUTING' WHERE id=? AND status='PENDING'",id)!=1)throw new ServiceException(409,"方案正在执行");Map<String,Object> p=json.readValue(String.valueOf(a.get("proposalJson")),new TypeReference<>(){});int n="CREATE_VOUCHERS".equals(a.get("actionType"))?vouchers(sid,String.valueOf(a.get("title")),p):notify(sid,String.valueOf(a.get("title")),p);jdbc.update("UPDATE growth_agent_action SET status='EXECUTED',executed_at=NOW() WHERE id=?",id);return Map.of("id",id,"status","EXECUTED","affectedUsers",n,"message","Agent 操作已执行，并已写入审计记录");}catch(ServiceException e){throw e;}catch(Exception e){try{jdbc.update("UPDATE growth_agent_action SET status='FAILED' WHERE id=? AND status='EXECUTING'",id);}catch(Exception ignored){}throw migration(e);}}
    @Override public List<Map<String,Object>> listActions(Long mid,Long sid,int limit){try{return jdbc.queryForList("SELECT id,action_type AS actionType,title,status,created_at AS createdAt,executed_at AS executedAt FROM growth_agent_action WHERE merchant_id=? AND store_id=? ORDER BY id DESC LIMIT ?",mid,sid,Math.max(1,Math.min(50,limit)));}catch(Exception e){throw migration(e);}}
    private int notify(Long sid,String title,Map<String,Object> p){List<Long> ids=users(sid,num(p.get("targetDays"),30,90));String m=String.valueOf(p.getOrDefault("message","FIKA 为你准备了一条门店提醒。"));for(Long u:ids)jdbc.update("INSERT INTO user_notification (user_id,type,title,content,read_status,created_at) VALUES (?,'GROWTH_AGENT',?,?,0,NOW())",u,title,m);return ids.size();}
    private int vouchers(Long sid,String title,Map<String,Object> p){List<Long> ids=users(sid,num(p.get("targetDays"),30,90));int d=num(p.get("discount"),8,100),min=num(p.get("minimum"),48,1000),exp=num(p.get("expiresDays"),3,30);String m=String.valueOf(p.getOrDefault("message","FIKA 为你准备了一张限时优惠券。"));for(Long u:ids){String no="AG"+UUID.randomUUID().toString().replace("-","").substring(0,18).toUpperCase(Locale.ROOT);jdbc.update("INSERT INTO user_voucher (user_id,voucher_no,name,discount,minimum,status,source,created_at,expires_at) VALUES (?,?,?,?,?,0,'GIFT',NOW(),DATE_ADD(NOW(),INTERVAL ? DAY))",u,no,title,d,min,exp);jdbc.update("INSERT INTO user_notification (user_id,type,title,content,read_status,created_at) VALUES (?,'GROWTH_AGENT',?,?,0,NOW())",u,title,m);}return ids.size();}
    private List<Long> users(Long sid,int days){return jdbc.queryForList("SELECT user_id FROM user_order WHERE store_id=? AND user_id IS NOT NULL AND created_at>=DATE_SUB(NOW(),INTERVAL ? DAY) GROUP BY user_id ORDER BY MAX(id) DESC LIMIT "+TARGET_LIMIT,Long.class,sid,days);}
    // 与商家总览完全共用口径：按订单创建日统计已完成订单。部分历史订单没有 completed_at，不能因此从增长诊断中消失。
    private Map<String,Object> snapshot(Long sid){return Map.of("todayOrders",count("SELECT COUNT(*) FROM user_order WHERE store_id=? AND DATE(created_at)=CURDATE() AND status<>'UNPAID'",sid),"todayRevenue",amount("SELECT COALESCE(SUM(final_price),0) FROM user_order WHERE store_id=? AND DATE(created_at)=CURDATE() AND status='COMPLETED'",sid),"pendingOrders",count("SELECT COUNT(*) FROM user_order WHERE store_id=? AND status IN ('PENDING','PREPARING')",sid),"weekRevenue",amount("SELECT COALESCE(SUM(final_price),0) FROM user_order WHERE store_id=? AND created_at>=DATE_SUB(NOW(),INTERVAL 7 DAY) AND status='COMPLETED'",sid),"flashSaleStock",count("SELECT COALESCE(SUM(available_stock),0) FROM flash_sale_activity WHERE store_id=? AND enabled=1 AND NOW() BETWEEN start_at AND end_at",sid));}
    private Map<String,Object> storeMeta(Long storeId){try{return jdbc.queryForMap("SELECT code,name FROM store WHERE id=?",storeId);}catch(Exception ignored){return Map.of("code","","name","当前门店");}}
    private long count(String s,Long id){try{return jdbc.queryForObject(s,Long.class,id);}catch(Exception e){return 0;}}private double amount(String s,Long id){try{BigDecimal r=jdbc.queryForObject(s,BigDecimal.class,id);return r==null?0:r.doubleValue();}catch(Exception e){return 0;}}private Map<String,Object> signal(String l,String v,String n){return Map.of("label",l,"value",v,"note",n);}private int num(Object v,int d,int max){try{return Math.max(1,Math.min(max,Integer.parseInt(String.valueOf(v))));}catch(Exception e){return d;}}private String money(double n){return String.format(Locale.ROOT,"%.2f",n);}private ServiceException migration(Exception e){return new ServiceException(500,"店长 Agent 审计表尚未初始化，请先执行 V20260809_10_growth_agent.sql");}
}
